const router = require('express').Router();
const c = require('../controllers/orders.controller');
const { authenticate, authorize } = require('../middleware/auth.middleware');
router.use(authenticate);
router.get('/', c.getOrders);
router.post('/', authorize('admin','branch_manager','receptionist'), c.createOrder);
router.get('/:id', c.getOrderById);
router.patch('/:id/status', c.updateStatus);
router.patch('/:id/assign', authorize('admin','branch_manager'), c.assignTechnician);
router.post('/:id/parts', authorize('admin','branch_manager','technician','warehouse','customer_service'), c.addPart);
module.exports = router;
