const router = require('express').Router();
const c = require('../controllers/suppliers.controller');
const { authenticate, authorize } = require('../middleware/auth.middleware');
router.use(authenticate);
router.get('/',        c.getSuppliers);
router.get('/:id',     c.getSupplierById);
router.post('/',       authorize('admin','branch_manager'), c.createSupplier);
router.put('/:id',     authorize('admin','branch_manager'), c.updateSupplier);
router.delete('/:id',  authorize('admin'), c.deleteSupplier);
module.exports = router;
